'use client';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app'
// };

export default function RootLayout({ children, ...props }) {
	return (
		<html lang="en">
			<title>Register Login</title>
			<body className={inter.className}>
				<ProgressBar />
				<Toaster />
				<SessionProvider session={props.session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
