'use client';
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';
import { NextAuthProvider } from '@/components/provider';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<title>Register Login</title>
			<meta name="description" content="Generated by create next app" />
			<body className={inter.className}>
				<ProgressBar />
				<Toaster />
				<NextAuthProvider>
					<Navbar />
					{children}
				</NextAuthProvider>
			</body>
		</html>
	);
}
